// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepterAPI.Infrastructure;

namespace RepterAPI.Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230125202841_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RepterAPI.Infrastructure.Model.Jarat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Atszallas")
                        .HasColumnType("int");

                    b.Property<int?>("CelVarosId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Indulas")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KiinduloVarosId")
                        .HasColumnType("int");

                    b.Property<double>("KmDij")
                        .HasColumnType("float");

                    b.Property<int?>("LegitarsasagId")
                        .HasColumnType("int");

                    b.Property<int>("RepulesiIdo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CelVarosId");

                    b.HasIndex("KiinduloVarosId");

                    b.HasIndex("LegitarsasagId");

                    b.ToTable("Jaratok");
                });

            modelBuilder.Entity("RepterAPI.Infrastructure.Model.Legitarsasag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Legitarsasag");
                });

            modelBuilder.Entity("RepterAPI.Infrastructure.Model.Varos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nepesseg")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Varosok");
                });

            modelBuilder.Entity("RepterAPI.Infrastructure.Model.Jarat", b =>
                {
                    b.HasOne("RepterAPI.Infrastructure.Model.Varos", "CelVaros")
                        .WithMany()
                        .HasForeignKey("CelVarosId");

                    b.HasOne("RepterAPI.Infrastructure.Model.Varos", "KiinduloVaros")
                        .WithMany()
                        .HasForeignKey("KiinduloVarosId");

                    b.HasOne("RepterAPI.Infrastructure.Model.Legitarsasag", "Legitarsasag")
                        .WithMany()
                        .HasForeignKey("LegitarsasagId");

                    b.Navigation("CelVaros");

                    b.Navigation("KiinduloVaros");

                    b.Navigation("Legitarsasag");
                });
#pragma warning restore 612, 618
        }
    }
}
